#!/bin/bash
#
# Author: Pride Leong<lykling.lyk@gmail.com>
# Date: Wed Jun 21 12:18:13 CST 2017
# Brief:
#   Get all git objects
# Arguments:
#   -h:             show help document
#   -t:             show object type
# Returns:
#   succ: 0
#   fail: 1

# Flags
#set -u
#set -e
set -o pipefail

# Exit code
readonly EX_SUCC=0
readonly EX_FAIL=1


# Usage
function usage() {
    echo "Usage: $0 [-h|--help] [-t|--show-type]"
    echo '
Options:
    -h|--help           print this and exit
    -t|--show-type      show object type
'
}


# Get object list
function get_object_list() {
    # Get packed object list
    find $(git rev-parse --git-dir)/objects/pack -name 'pack-*.idx' \
        | while read p ; do git show-index < $p | cut -f2 -d' '; done
    # Get loose object list
    find $(git rev-parse --git-dir)/objects -type f \
        | grep -E '[0-9a-f]{2}/[0-9a-f]{38}' \
        | sed -e 's:.*\([0-9a-f]\{2\}\)/\([0-9a-f]\{38\}\):\1\2:'
}


# Main entry
function main() {
    opts=($(getopt -o 'ht' -l 'help,show-type' -- "$@"))
    for ((i = 0; i < ${#opts[@]}; ++i)); do
        flag=${opts[$i]}
        case ${flag} in
            -h|--help)
                show_help=1
                ;;
            -t|--show-type)
                show_type=1
                ;;
            *)
                ;;
        esac
    done
    if [[ "${show_help}" == "1" ]]; then
        usage
        exit $EX_SUCC
    fi
    list=($(get_object_list))
    for item in "${list[@]}"; do
        if [[ "${show_type}" == "1" ]]; then
            echo "$(git cat-file -t ${item}) ${item}"
        else
            echo ${item}
        fi
    done
}


main "$@"
