#!/bin/bash

JDKS=(`/usr/bin/ls /opt/java/ | grep jdk`)
JRES=(`/usr/bin/ls /opt/java/ | grep jre`)

function usage() {
    echo "Usage: $0 <jdk|jre> <cmd>";
}

if [[ $# -lt 1 ]]
then
    usage;
    exit 1;
fi

case $1 in
    "jdk"|"JDK")
        case $2 in
            "set")
                choice=$3;
                ln -snf /opt/Java/${JDKS[$choice]} /etc/jvm/java_home
                #for i in `seq 0 $((${#JDKS[@]} - 1))`
                #do
                    #PATH=${PATH/\/opt\/Java\/${JDKS[$i]}/bin:/};
                #done
                #export JAVA_HOME=\/opt\/Java\/${JDKS[$choice]};
                #export PATH=\/opt\/Java\/${JDKS[$choice]}/bin:$PATH;
                ;;
            "list")
                for i in `seq 0 $((${#JDKS[@]} - 1))`
                do
                    echo "[$i] ${JDKS[$i]}";
                done
                ;;
            *)
                usage;
                exit 1;
                ;;
        esac
        ;;
    "jre"|"JRE")
        case $2 in
            "set")
                choice=$3;
                ln -snf /opt/Java/${JDKS[$choice]} /etc/jvm/java_home
                #for i in `seq 0 $((${#JRES[@]} - 1))`
                #do
                    #PATH=${PATH/\/opt\/Java\/${JRES[$i]}/bin:/};
                #done
                #export JAVA_HOME=\/opt\/Java\/${JRES[$choice]};
                #export PATH=\/opt\/Java\/${JRES[$choice]}/bin:$PATH;
                ;;
            "list")
                for i in `seq 0 $((${#JRES[@]} - 1))`
                do
                    echo "[$i] ${JRES[$i]}";
                done
                ;;
            *)
                usage;
                exit 1;
                ;;
        esac
        ;;
    *)
        usage;
        exit 1;
        ;;
esac

